name: ScopeBench Getting to Green

on:
  pull_request:
  workflow_dispatch:

jobs:
  scopebench-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install ScopeBench
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run quickstart smoke
        run: |
          scopebench quickstart --json --out-dir .scopebench-artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scopebench-quickstart-artifacts
          path: .scopebench-artifacts
